jwt:
  secret: secrectkey123 

server:
    port: 8081         
    
    
spring:
    application:
           name: Tourism_App_JWT_Services
    data:
        mongodb:
            uri: mongodb+srv://userAdminSD:AZA5KCbTc6sUoVrQ@cluster0.72tkw.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            