server:
    port: 8083
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: Tourism_App_Admin
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/**
      - id: Tourism_App_User
        uri: http://localhost:8080/
        predicates:
        - Path=/api/v1/**
      - id: TourismApp_JWTServices
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/**         
      
  